### ISSUE TITLE
IFrame needs width and height

### ISSUE THREAD

**Issue by lexnederbragt** [ProblemSolvingIO/parsons#1]
The page http://parsons.problemsolving.io says to use `IFrame('puzzle url')` but for me this throws an error: 

>TypeError: __init__() missing 2 required positional arguments: 'width' and 'height'

I guess the correct usage is `IFrame('puzzle url', 1000, 400)` (or other numbers for width and height)

**Comment by shlomihod** [comment]
Thanks! fixed 106f2396
