### ISSUE TITLE
Website no longer available

### ISSUE THREAD

**Issue by jrobinson-uk** [ProblemSolvingIO/parsons#11]
We host some content that points at http://parsons.problemsolving.io/, is this no longer available, is there an alternative?

**Comment by shlomihod** [comment]
Thank you for letting me know. The domain was expired and I wasn't sure whether people are using the website. I've just registered it again. It should work again soon.

**Comment by GregS83** [comment]
Still not working...

**Comment by jcumby** [comment]
We also make quite a lot of use of the website for teaching @Edinburgh-Chemistry-Teaching. Is the domain likely to be re-registered, or is there an alternative solution (we embed the problems in Jupyter notebooks)? It's a great tool!

**Comment by rfpg** [comment]
We also use it at GW here in DC, USA. Would be great to see it live again!

**Comment by andreasdh** [comment]
The webpage went up again last year but has now been down again for a couple of months. We use the webpage a lot in our teaching at the University of Oslo, and we would appreciate a lot if the page worked again.

**Comment by shlomihod** [comment]
Thank you so much for your feedback, I didn't know that the website is being used by so many people!

Apparently, Heroku  (could provider) canceled their free plan, and I'll need to transfer the website to another platform. I plan to work on that in the next few days.

I'll keep you posted!

**Comment by andreasdh** [comment]
Great! Thanks a lot, and thank you for a great site which I have used a lot the past few years!

**Comment by rfpg** [comment]
Any updates on the site? I'd like to use it for a course build out this semester!

**Comment by shlomihod** [comment]
I am grateful for your understanding during the recent downtime of the website. I am pleased to announce that the website is now fully functional, as I had to make the transition from Heroku to PythonAnywhere.

It is very exciting to know that people find this website so useful.

**Comment by rickygraham** [comment]
Hello! Is there any way to recover previously created Parsons problems, created prior to the downtime? Currently, I get:
<img width="547" alt="Screen Shot 2023-02-24 at 2 16 18 PM" src="https://user-images.githubusercontent.com/1520435/221271207-31536b68-af67-412d-a5e9-cb8eba55cc6f.png">

**Comment by shlomihod** [comment]
Unfortunately, the data from the previous server couldn't be transferred to the new server. I apologize for that.

**Comment by rickygraham** [comment]
No worries! Thanks for putting the site back-up and I hope it will stay around. It's really great!

**Comment by shlomihod** [comment]
Thanks!
